version: "3.8"

services:

  # Microsserviços
  profinance:
    container_name: profinance
    image: gabriellagrota/profinance:latest
    restart: always
    build:
      context: .
    environment:
      TZ: America/Sao_Paulo
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    depends_on:
      - profinance-db
    networks:
      - app-network

  # Bancos de Dados PostgreSQL
  profinance-db:
    image: postgres:15
    container_name: profinance-db
    restart: always
    environment:
      POSTGRES_DB: profinance
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
    driver: local