spring:
  application:
    name: Profinance

  # Database connection
  datasource:
    url: jdbc:${DB_URL}?useTimezone=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # Database (JPA)
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate.ddl-auto: validate
    hibernate:
      ddl-auto: validate
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        generate_statistics: false
        format_sql: true

  # Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baselineVersion: 1

# Swagger
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /documentacao-api
    operationsSorter: method
    tagsSorter: alpha

# Security
jwt:
  secret: ${JWT_SECRET}

# Actuator
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
      group:
        liveness:
          include: livenessState, ping
        readiness:
          include: readinessState, ping
      show-details: "NEVER"
      probes:
        enabled: true
  health:
    ping:
      enabled: true
    diskspace:
      enabled: false
    livenessState:
      enabled: true
    readinessState:
      enabled: true

URL_FRONT: ${URL_FRONTEND}